version: "3.1"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nearbyshops:latest
    network_mode: host
    ports: 
      - "8000:8000"
    restart: "always"
    env_file:
      - nearbyshops/.env